[available_card]
# title=You are modifying Available AddOn card.
# files=
# folders=src/components/available-add-ons
# check-list=Available addon components are referenced below, please make sure your changes will not affect.\n\n1. New billing portal available list\n2. Discover more products under the Standalone portal (you can verify it by switching to the standalone page in the upper right corner under npm run mock, for more information you can reach out Lyman Shi)